buildscript {
    repositories {
        maven { url = 'http://files.minecraftforge.net/maven' }
        mavenCentral()
        maven { url = 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:1.2-SNAPSHOT'
    }
}

apply plugin: 'forge'

minecraft {
    version = '1.6.4-9.11.1.965'
    runDir = 'eclipse'
}

version = '1.0'
group = 'com.agadar.bettervanilla'
archivesBaseName = 'BetterVanilla-164'

sourceSets {
    main {
        java {
            srcDir 'java'
        }
        resources {
            srcDir 'resources'
        }
    }
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': project.minecraft.version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

jar {
    archiveName = 'BetterVanilla-164.jar'
}
