package net.minecraft.init;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
public class Blocks {
    private static Block b() { return new Block(Material.rock); }
    public static final Block leaves = b();
    public static final Block sand = b();
    public static final Block planks = b();
    public static final Block cauldron = b();
    public static final Block bed = b();
    public static final Block bookshelf = b();
    public static final Block cactus = new net.minecraft.block.BlockCactus();
    public static final Block hopper = b();
    public static final Block dirt = b();
    public static final Block gravel = b();
    public static final Block web = b();
    public static final Block cobblestone = b();
    public static final Block wool = b();
    public static final Block stained_hardened_clay = b();
    public static final Block hardened_clay = b();
    public static final Block vine = b();
    public static final Block pumpkin = b();
    public static final Block melon_block = b();
    public static final Block log = b();
    public static final Block log2 = b();
    public static final Block stone = b();
    public static final Block mossy_cobblestone = b();
    public static final Block stonebrick = b();
    public static final Block stone_slab = b();
    public static final Block end_stone = b();
    public static final Block grass = b();
    public static final Block mycelium = b();
    public static final Block brown_mushroom = b();
    public static final Block red_mushroom = b();
    public static final Block nether_wart = b();
    public static final Block ice = b();
    public static final Block flowing_water = b();
    public static final Block water = b();
    public static final Block ender_chest = b();
    public static final Block detector_rail = b();
    public static final Block activator_rail = b();
    public static final Block gold_block = b();
    public static final Block golden_rail = b();
    public static final Block piston = b();
    public static final Block sticky_piston = b();
    public static final Block anvil = b();
    public static final Block heavy_weighted_pressure_plate = b();
    public static final Block light_weighted_pressure_plate = b();
    public static final Block air = b();
}
