package net.minecraft.init;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemArmor.ArmorMaterial;
public class Items {
    private static Item it() { return new Item(); }
    private static ItemArmor armor(ArmorMaterial mat, int type, int slot) { return new ItemArmor(mat, type, slot); }
    public static final Item apple = it();
    public static final Item gunpowder = it();
    public static final Item glass_bottle = it();
    public static final Item potionitem = it();
    public static final Item ender_pearl = it();
    public static final Item milk_bucket = it();
    public static final Item bucket = it();
    public static final Item water_bucket = it();
    public static final Item lava_bucket = it();
    public static final Item feather = it();
    public static final Item chicken = it();
    public static final Item cooked_chicken = it();
    public static final Item dye = it();
    public static final Item wheat_seeds = it();
    public static final Item flint = it();
    public static final Item cauldron = it();
    public static final Item iron_ingot = it();
    public static final Item iron_door = it();
    public static final Item iron_helmet = armor(ArmorMaterial.IRON, 0, 0);
    public static final Item iron_chestplate = armor(ArmorMaterial.IRON, 0, 1);
    public static final Item iron_leggings = armor(ArmorMaterial.IRON, 0, 2);
    public static final Item iron_boots = armor(ArmorMaterial.IRON, 0, 3);
    public static final Item iron_sword = it();
    public static final Item iron_shovel = it();
    public static final Item iron_pickaxe = it();
    public static final Item iron_hoe = it();
    public static final Item iron_axe = it();
    public static final Item shears = new net.minecraft.item.ItemShears();
    public static final Item redstone = it();
    public static final Item compass = it();
    public static final Item minecart = it();
    public static final Item leather = it();
    public static final Item string = it();
    public static final Item paper = it();
    public static final Item name_tag = it();
    public static final Item saddle = it();
    public static final Item wooden_door = it();
    public static final Item clock = it();
    public static final Item gold_ingot = it();
    public static final Item golden_apple = it();
    public static final Item golden_helmet = armor(ArmorMaterial.GOLD, 0, 0);
    public static final Item golden_chestplate = armor(ArmorMaterial.GOLD, 0, 1);
    public static final Item golden_leggings = armor(ArmorMaterial.GOLD, 0, 2);
    public static final Item golden_boots = armor(ArmorMaterial.GOLD, 0, 3);
    public static final Item golden_sword = it();
    public static final Item golden_shovel = it();
    public static final Item golden_pickaxe = it();
    public static final Item golden_hoe = it();
    public static final Item golden_axe = it();
    public static final Item bed = it();
    public static final Item rotten_flesh = it();
    public static final Item beef = it();
    public static final Item porkchop = it();
    public static final Item fermented_spider_eye = it();
    public static final Item slime_ball = it();
    public static final Item clay_ball = it();
    public static final Item reeds = it();
    public static final Item diamond = it();
    public static final Item flint_and_steel = it();
    public static final Item chainmail_helmet = armor(ArmorMaterial.CHAIN, 0, 0);
    public static final Item chainmail_chestplate = armor(ArmorMaterial.CHAIN, 0, 1);
    public static final Item chainmail_leggings = armor(ArmorMaterial.CHAIN, 0, 2);
    public static final Item chainmail_boots = armor(ArmorMaterial.CHAIN, 0, 3);
    public static final Item iron_horse_armor = it();
    public static final Item golden_horse_armor = it();
    public static final Item diamond_horse_armor = it();
    public static final Item blaze_rod = it();
    public static final Item brewing_stand = it();
    public static final Item pumpkin_seeds = it();
    public static final Item melon_seeds = it();
    public static final Item nether_wart = it();
    public static final Item spider_eye = it();
    public static final Item blaze_powder = it();
    public static final Item magma_cream = it();
    public static final Item ghast_tear = it();
    public static final Item gold_nugget = it();
    public static final Item sugar = it();
    public static final Item glistering_melon = it();
    public static final Item water_bucket2 = it();
}
